// These are the test files in this dir to be run.
var tests = [
  { path: "empty-baseline.pde", tags: ["Calibration"] },
  { path: "background.pde", tags: ["2D"] },
  { path: "random-ellipse.pde", tags: ["2D"] },
  { path: "random-point.pde", tags: ["2D"] },
  { path: "random-fill.pde", tags: ["2D"] },
  { path: "random-line.pde", tags: ["2D"] },
  { path: "triangle.pde", tags: ["2D"] },
  { path: "arc.pde", tags: ["2D"] },
  { path: "pimage-resize.pde", tags: ["2D", "PImage"] },
  { path: "pimage-mask-image.pde", tags: ["2D", "PImage"] },
  { path: "pimage-copy.pde", tags: ["3D", "PImage"] },
  { path: "pimage-filter-threshold.pde", tags: ["2D", "PImage"] },
  { path: "pimage-filter-gray.pde", tags: ["2D", "PImage"] },
  { path: "pimage-filter-invert.pde", tags: ["2D", "PImage"] },
  { path: "pimage-filter-posterize4.pde", tags: ["2D", "PImage"] },
  { path: "pimage-filter-blur3.pde", tags: ["2D", "PImage"] },
  { path: "pimage-filter-opaque.pde", tags: ["2D", "PImage"] },
  { path: "pimage-filter-erode.pde", tags: ["2D", "PImage"] },
  { path: "pimage-filter-dilate.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-blend.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-add.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-subtract.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-darkest.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-lightest.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-difference.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-exclusion.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-multiply.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-screen.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-overlay.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-hardlight.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-softlight.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-dodge.pde", tags: ["2D", "PImage"] },
  { path: "pimage-blend-burn.pde", tags: ["2D", "PImage"] },
  { path: "rainbow-spirograph.pde", tags: ["2D"] },
  { path: "plants.pde", tags: ["2D"] }
];
